### ISSUE TITLE
Update documentation to show Groovy parameter for Automatically create/update process Parameter

### ISSUE THREAD

**Issue by mundhras** [jenkinsci/uipath-automation-package-plugin#131]
Could we please update the groovy script documentation to show how to pass the "Automatically create/update process" parameter

**Comment by ThomasStockerUiPath** [comment]
Issue solve.
Here is the updated documentation:
https://docs.uipath.com/test-suite/automation-suite/2023.4/user-guide/executing-tasks-cli
