### ISSUE TITLE
Groovy Script auto creation

### ISSUE THREAD

**Issue by mundhras** [jenkinsci/uipath-automation-package-plugin#132]
### What feature do you want to see added?

It would to be good to have a way to generate the Groovy Script based on what you enter using the UIi interface in jenkins

**Comment by ThomasStockerUiPath** [comment]
Thx for the feedback. This request seems to be rather for Jenkins itself not for our plugin.
As you might know, Jenkins already offers the possiblity to convert ui configurations into a pipeline script using their snippet generator.
