### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Apyz** [jenkinsci/uipath-automation-package-plugin#134]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

operating system: windows7
IDE: intellij IDEA Community Edition

### Reproduction steps

package ui_automation;

import mmarquee.automation.UIAutomation;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        UIAutomation automation = UIAutomation.getInstance();

        System.out.println( "Hello World!" );
    }
}

### Expected Results

Be able to perform correctly

### Actual Results

"C:\Program Files\Java\jdk1.8.0_341\bin\java.exe" -javaagent:D:\Backup\Downloads\ideaIC-2022.2.2.win\lib\idea_rt.jar=51783:D:\Backup\Downloads\ideaIC-2022.2.2.win\bin -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_341\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\UiPathBridge.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_341\jre\lib\rt.jar;D:\irapy_x64_2022_IDEA\ui-automation\ui-automation-demo\target\classes;F:\Maven_Repository\com\github\mmarquee\ui-automation\0.7.0\ui-automation-0.7.0.jar;F:\Maven_Repository\net\java\dev\jna\jna\5.6.0\jna-5.6.0.jar;F:\Maven_Repository\net\java\dev\jna\jna-platform\5.6.0\jna-platform-5.6.0.jar;F:\Maven_Repository\org\apache\logging\log4j\log4j-api\2.17.1\log4j-api-2.17.1.jar;F:\Maven_Repository\org\apache\logging\log4j\log4j-core\2.17.1\log4j-core-2.17.1.jar;F:\Maven_Repository\com\google\code\findbugs\findbugs\3.0.1\findbugs-3.0.1.jar;F:\Maven_Repository\net\jcip\jcip-annotations\1.0\jcip-annotations-1.0.jar;F:\Maven_Repository\com\google\code\findbugs\jsr305\2.0.1\jsr305-2.0.1.jar;F:\Maven_Repository\com\google\code\findbugs\bcel-findbugs\6.0\bcel-findbugs-6.0.jar;F:\Maven_Repository\com\google\code\findbugs\jFormatString\2.0.1\jFormatString-2.0.1.jar;F:\Maven_Repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;F:\Maven_Repository\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar;F:\Maven_Repository\org\ow2\asm\asm-debug-all\5.0.2\asm-debug-all-5.0.2.jar;F:\Maven_Repository\org\ow2\asm\asm-commons\5.0.2\asm-commons-5.0.2.jar;F:\Maven_Repository\org\ow2\asm\asm-tree\5.0.2\asm-tree-5.0.2.jar;F:\Maven_Repository\org\ow2\asm\asm\5.0.2\asm-5.0.2.jar;F:\Maven_Repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;F:\Maven_Repository\com\apple\AppleJavaExtensions\1.4\AppleJavaExtensions-1.4.jar;F:\Maven_Repository\jaxen\jaxen\1.1.6\jaxen-1.1.6.jar" ui_automation.App
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Exception in thread "main" java.lang.NullPointerException
	at com.sun.jna.platform.win32.COM.COMInvoker._invokeNativeObject(COMInvoker.java:43)
	at com.sun.jna.platform.win32.COM.Unknown.QueryInterface(Unknown.java:70)
	at mmarquee.automation.UIAutomation.<init>(UIAutomation.java:101)
	at mmarquee.automation.UIAutomation.getInstance(UIAutomation.java:147)
	at ui_automation.App.main(App.java:13)

Process finished with exit code 1

**Comment by ThomasStockerUiPath** [comment]
Hi Apyz,
I do not see any reference to our plugin in your error description.
