### ISSUE TITLE
Enable Release Drafter

### ISSUE THREAD

**Issue by SaarthakMaini** [jenkinsci/uipath-automation-package-plugin#145]
### What feature do you want to see added?

[Release Drafter](https://github.com/toolmantim/release-drafter) is a tool and GitHub app which helps to automate the management of releases notes. This tool generates changelog drafts using pull request metadata (commit headers, links, etc.) and then suggest a changelog draft in GitHub Release

Release drafter can be used as a GitHub Application or as a GitHub action. The recommended approach is to use the GitHub Action as the GitHub App is [deprecated](https://github.com/release-drafter/release-drafter/blob/master/docs/github-app.md) and won’t receive new features anymore. Also, the Application does not produce logs which would be available to plugin maintainers, and hence it might be difficult to troubleshoot errors if they occur.

**Comment by ThomasStockerUiPath** [comment]
Thx for the feedback SaarthakMani, 
we will have a look at it.
