### ISSUE TITLE
Which version of the plugin support orchestrator 2019.10.19

### ISSUE THREAD

**Issue by smartaquarius10** [jenkinsci/uipath-automation-package-plugin#38]
Team,

Could you please confirm which release version of this plugin supports orchestrator 2019.10.19?

Thank you

**Comment by bogdancucosel** [comment]
HI @smartaquarius10 , any version starting from 2.0.0 should work, although we would recommend using the last one released, 2.2.0 at this time.

Is there a particular scenario where things do not work with 19.10 release of Orchestrator ?

Thanks,
Bogdan

**Comment by smartaquarius10** [comment]
@bogdancucosel , Some mistake at my end it is working now thanks :)
