### ISSUE TITLE
Is it possible to activate the package?

### ISSUE THREAD

**Issue by smartaquarius10** [jenkinsci/uipath-automation-package-plugin#40]
Hello,

Is there anyway to activate the package using this plugin. If yes, can any one share the syntax for it.

Thank you

**Comment by bogdancucosel** [comment]
Hi @smartaquarius10 , not sure what you mean with activate. If you mean publish the package and update the process, you can do that with UiPath Deploy https://plugins.jenkins.io/uipath-automation-package/
