### ISSUE TITLE
How to manage assets in jenkinsfile

### ISSUE THREAD

**Issue by smartaquarius10** [jenkinsci/uipath-automation-package-plugin#41]
Hello,

Generally we save credentials in orchestrator assets. In this plugin we have option of saving assets also but the question is how to manage them within jenkinsfile. 

From CI/CD perspective, it is preferred to upload jenkinsfile in github repo. But, none of the organizations allows us to check in credentials in jenkinsfile. 

Could you please suggest any design pattern which can help in management of assets in case of webhook.

**Comment by bogdancucosel** [comment]
Hi @smartaquarius10 I guess that would depend on the use case. In some cases we are storing the credentials in a third party key vault and fetch those when deploying the assets. Guess you could use something similar to https://plugins.jenkins.io/azure-keyvault/ depending on what sort of key vaults would be available in your case.
