### ISSUE TITLE
Any alternative of using credential Id loaded in jenkins?

### ISSUE THREAD

**Issue by smartaquarius10** [jenkinsci/uipath-automation-package-plugin#42]
In our organisation, it is not allowed to save any credential in jenkins. As part of dev sec ops we pull our uipath credentials from vault at runtime. 

As per the plugin, the only possible way is to use credential id of jenkins. Is there any alternative to this. 

Please help.

**Comment by ThomasStockerUiPath** [comment]
@smartaquarius10  we do not plan to add alternative cred storage atm to our plugin. 
I would kindly ask you to alternatively use our [CLI ](https://www.myget.org/feed/uipath-dev/package/nuget/UiPath.CLI)within Jenkins.
this will allow you to pass in parameters at your own style.
For further questions pls let me know.
