### ISSUE TITLE
What is the purpose of orchestrator flags in UIPathPack section?

### ISSUE THREAD

**Issue by smartaquarius10** [jenkinsci/uipath-automation-package-plugin#43]
Team,

We can enable AutoVersionEntry class to create package versions automatically but what is the need of this code in the UIPathPack section:

```
          useOrchestrator: true,
          orchestratorAddress: "OrchestratorUrl",
          orchestratorTenant: "tenant name",
          credentials: [$class: 'AutoVersionEntry'”]
```

If we set this value **useOrchestrator: true**, does plugin fetch the current version from orchestrator and then evaluate the next number. Please suggest.

Thank you

**Comment by ThomasStockerUiPath** [comment]
@smartaquarius10 , 
while packing certain projects such as libraries or dependencies to libraries, we have to connect to Orchestrator to fetch those dependencies.
