### ISSUE TITLE
Auto versioning always update the last octet of version?

### ISSUE THREAD

**Issue by smartaquarius10** [jenkinsci/uipath-automation-package-plugin#56]
Team,

This plugin generates the version in 3 octet form like this

 - Major.Minor.BuildNumber

Whenever we use AutoVersionEntry class then this plugin increments only the last octet of the version which calling uipath pack. 

Is there anyway to increment other octets as well because version numbers like this **1.0.73221788** doesn't looks correct.

**Comment by robertstreche** [comment]
Hi, @smartaquarius10

The mechanism you described works as intended. The purpose of auto versioning method is to enable you to pack and deploy many different versions of the same project without overwriting the previous versions. Also, this feature give you the context to pack and/or deploy without being necessary to make any clean up before. So, that being said, the build number is just a differentiator and the reason this number is large is to ensure there will be no packages with the same version.

If you need to increment the major or the minor of the version you can do it manually by editing the project.json file.

**Comment by ThomasStockerUiPath** [comment]
@smartaquarius10 , if you want to choose your own version pls refer to the option 'Define custom package version'.
BR
Thomas
